### ISSUE TITLE
update in sds_newsletter_2021.Rmd

### ISSUE THREAD

**Issue by beanumber** [SmithCollege-SDS/sds-www#11]
As the newsletter author, I want you to write your own update, so that I don't have to write it for you. 

You can either commit the changes yourself, or just send me the text you want in an email. 

**Acceptance criteria**: The task is done when all members of the faculty have a short update in `sds_newsletter_2021.Rmd`

- [x] @RandiLGarcia 
- [x] @wjhopper 
- [x] @rudeboybert 
- [x] @kmkinnaird 
- [x] Scott
- [x] Lindsay
- [ ] Fatou

**Comment by rudeboybert** [comment]
@beanumber can you give us a deadline?

**Comment by beanumber** [comment]
July 15

**Comment by RandiLGarcia** [comment]
Done!

**Comment by beanumber** [comment]
Thanks to everyone for contributing to this! I drafted the rest of the letter, but it lacks some of the enthusiasm of years past. If anyone want to contribute more I'd welcome your help. Send a PR!
