### ISSUE TITLE
personal update for newsletter

### ISSUE THREAD

**Issue by beanumber** [SmithCollege-SDS/sds-www#12]
As the newsletter author, I want you to write your own update, so that I don't have to write it for you.

You can either commit the changes yourself, or just send me the `markdown text` you want in an email.

Acceptance criteria: The task is done when all members of the faculty have a short update in [`sds_newsletter_2022.qmd`](https://github.com/SmithCollege-SDS/sds-www/blob/master/www/sds_newsletter_2022.qmd). This needs to go out by August 1st (before JSM). 

- [x] @RandiLGarcia
- [ ] @wjhopper
- [x] @rudeboybert
- [x] @kmkinnaird
- [x] @scao53 
- [x] @lindsaypoirier 
- [x] @kaitlyncook 
- [ ] @lacombe129 
- [x] @Epsian 

You can read last year's newsletter [here](https://smithcollege-sds.github.io/sds-www/sds_newsletter_2021.html) to get a sense of what I'm looking for.

**Comment by RandiLGarcia** [comment]
I added my update directly.
