### ISSUE TITLE
personal update for newsletter 2023

### ISSUE THREAD

**Issue by beanumber** [SmithCollege-SDS/sds-www#17]
As the newsletter author, I want you to write your own update, so that I don't have to write it for you.

You can either commit the changes yourself, or just send me the markdown text you want in an email.

Acceptance criteria: The task is done when all members of the faculty have a short update in [sds_newsletter_2023.qmd](https://github.com/SmithCollege-SDS/sds-www/blob/master/www/sds_newsletter_2023.qmd). This needs to go out by July 15th (before JSM).

- [x] @RandiLGarcia
- [ ] @wjhopper
- [x] @rudeboybert
- [x] @kmkinnaird
- [ ] @scao53
- [ ] @lindsaypoirier
- [ ] @kaitlyncook
- [x] @lacombe129
- [ ] @Epsian
- [x] @caseyberger 

You can read last year's newsletter [here](https://smithcollege-sds.github.io/sds-www/sds_newsletter_2022.html) to get a sense of what we're looking for.

**Comment by RandiLGarcia** [comment]
Update added with commit #[91b5d35](https://github.com/SmithCollege-SDS/sds-www/commit/91b5d356a97ad8955b84dbaf861f678ede82d6b2)
